postgres:
  image: postgres:9.4.5
  environment:
    POSTGRES_USER: trangtungn
    POSTGRES_PASSWORD: 12345678
  ports:
    - '5433:5432'
  volumes:
    - ~/.docker-volumes/shines/postgresql/data:/var/lib/postgresql/data

shines:
  build: .
  links:
    - postgres
  volumes:
    - .:/shines
  ports:
    - '3030:8000'
  env_file:
    - .shines.env
